[server]
enableXsrfProtection = true
enableCORS = false
enableWebsocketCompression = true

[auth]
password = "EnaPayslip1990!"  # Change this
PAYSLIP_EMAIL = "bradenkipkirui@gmail.com"
PAYSLUB_APP_PASSWORD = "vxgi ozkz czer gcdp"
