# In ~/.streamlit/secrets.toml
[login]
username = "admin"
password = "1234"
username == st.secrets.login.username
password == st.secrets.login.password
PAYSLIP_EMAIL = "bradenkipkirui@gmail.com"
PAYSLUB_APP_PASSWORD = "vxgi ozkz czer gcdp"
